spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
feign:
  url: http://covid-compare-web-scraper-api.eu-west-1.elasticbeanstalk.com:8080
covid-api-base-url: https://covid-api.com/api/
covid-api-country-report-uri: reports?date=%s&iso=%s
